# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - dev
  
pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    type: string
    default: stage
    values:
      - stage
      - production
  - name: appMode
    type: string
    default: primary
    values:
      - primary
      - failover

variables:
  # Set group variables based on environment & mode
  - ${{ if and(eq(parameters.environment, 'production') ,eq(parameters.appMode, 'primary')) }}:
    - group: AWS Prod Credentials
  - ${{ if and(eq(parameters.environment, 'production') ,eq(parameters.appMode, 'failover')) }}:
    - group: AWS Prod Credentials
  - ${{ if and(eq(parameters.environment, 'stage') ,eq(parameters.appMode, 'primary')) }}:
    - group: AWS Non-Prod Credentials
  - ${{ if and(eq(parameters.environment, 'stage') ,eq(parameters.appMode, 'failover')) }}:
    - group: AWS Non-Prod Credentials

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm run install-app
  displayName: 'npm install and build'

- ${{ if eq(parameters.environment, 'stage') }}:
  - script: npm run deploy-stage
    displayName: Deploy Stage

- ${{ if eq(parameters.environment, 'production') }}:
  - script: npm run deploy-prod
    displayName: Deploy Production
