# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - dev
  
pool:
  vmImage: windows-latest

parameters:
  - name: environment
    type: string
    default: stage
    values:
      - stage
      - production

variables:
  # Set group variables based on environment & mode
  - ${{ if eq(parameters.environment, 'production') }}:
    - group: AWS Cognito Production Credentials
  - ${{ if eq(parameters.environment, 'stage') }}:
    - group: AWS Non-Prod Credentials

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.18.x'
  displayName: 'Install Node.js'

- script: npm run install-app
  displayName: 'Install Dependencies'

- ${{ if eq(parameters.environment, 'stage') }}:
  - script: npm run deploy:non-prod
    displayName: Deploy Stage

- ${{ if eq(parameters.environment, 'production') }}:
  - script: npm run deploy:prod
    displayName: Deploy Production
